config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'catalogs#index'

  get 'cart/index'
  resources :catalogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/catalog.rb
# frozen_string_literal: true

class Catalog < ApplicationRecord
  belongs_to :offer, optional: true

  validates :code, :title, :price, presence: true
  validates :code, uniqueness: true
end

app/models/offer.rb
# frozen_string_literal: true

class Offer < ApplicationRecord
  has_many :catalogs

  validates :name, :code, presence: true
  validates :code, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/cart_controller.rb
# frozen_string_literal: true

class CartController < ApplicationController
  SPLIT_PATTERN = ','

  # GET /cart/index
  def index
    article_codes_string = 'VOUCHER, TSHIRT, MUG'
    article_codes_array = article_codes_string.blank? ? nil : article_codes_string.gsub(/\s+/, '').split(SPLIT_PATTERN)

    if article_codes_array.blank?
      flash[:alert] = t('views.messages.alert.nothing_sended')
      redirect_to controller: 'catalogs', action: 'index'
    else
      @total_amount = get_total_amount(article_codes_array)
      @articles = get_articles_hash(article_codes_array)

      if @total_amount.nil? || @total_amount <= 0 || @articles.blank?
        flash[:alert] = t('views.messages.alert.something_wrong')
        redirect_to controller: 'catalogs', action: 'index'
      else
        flash[:notice] = t('views.messages.notice.cart_success')
      end
    end
  end

  private

  def get_total_amount(article_codes_array)
    pricing_rules = get_catalog_articles_from_array(article_codes_array)
    co = Checkout.new(pricing_rules)
    article_codes_array.each do |article_code|
      co.scan(article_code)
    end
    co.total
  end

  def get_articles_hash(article_codes_array)
    articles_hash = []
    catalog_articles = get_catalog_articles_from_array(article_codes_array)
    catalog_articles.each do |catalog_article|
      co = Checkout.new(catalog_articles)
      article_array = article_codes_array.find_all { |article| article == catalog_article.code }

      article_array.each do |article_code|
        co.scan(article_code)
      end
      tmp_hash = {}
      tmp_hash['image'] = catalog_article.image.blank? ? '' : catalog_article.image
      tmp_hash['title'] = catalog_article.title.blank? ? '' : catalog_article.title
      tmp_hash['price'] = catalog_article.price.blank? ? 0 : catalog_article.price
      tmp_hash['quantity'] = article_array.blank? ? 0 : article_array.count
      tmp_hash['subtotal'] = tmp_hash['price'] * tmp_hash['quantity']
      tmp_hash['offer'] = catalog_article.offer.nil? ? false : true
      tmp_hash['total'] = co.total
      articles_hash << tmp_hash
    end
    articles_hash
  end

  def get_catalog_articles_from_array(article_codes_array)
    Catalog.where(code: article_codes_array.uniq)
  end
end

app/controllers/catalogs_controller.rb
# frozen_string_literal: true

class CatalogsController < ApplicationController

  # GET /catalogs
  def index
    @catalogs = Catalog.includes(:offer).all
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def catalog_params
    params.require(:catalog).permit(:title, :description, :image, :price, :code, :discount_percentage, :discount_volume)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/cart/_carts_stats.html.erb
<style>
  .center {
    text-align: center;
  }
</style>
<div class="table-responsive" style="width:100%;">
  <table id="tableCarts" class="table table-striped">
    <thead>
    <tr>
      <th><%= t('views.cart.article') %></th>
      <th class="center"><%= t('views.cart.price') %></th>
      <th class="center"><%= t('views.cart.quantity') %></th>
      <th class="center"><%= t('views.cart.subtotal') %></th>
      <th class="center"><%= t('views.cart.offer') %></th>
      <th class="center"><%= t('views.cart.total') %></th>
    </tr>
    </thead>
    <tbody>
    <% unless @articles.blank? %>
      <% @articles.each do |article| %>
        <tr>
          <td><%= image_tag (article['image']), style: "width: 30px; height:30px; margin: 2px" %> <%= article['title'] %></td>
          <td class="center"><%= number_to_currency(article['price'].to_f / 100) %></td>
          <td class="center"><%= article['quantity'] %></td>
          <td class="center"><%= number_to_currency(article['subtotal'].to_f / 100) %></td>
          <% if article['offer'] %>
            <td class="center"><span class='icon'><i class='fa fa-check' style="color: green"></i></span></td>
          <% else %>
            <td class="center"><span class='icon'><i class='fa fa-times' style="color: red"></i></span></td>
          <% end %>
          <td class="center"><strong><%= number_to_currency(article['total'].to_f / 100) %></strong></td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>

<%= javascript_include_tag "search_table_carts" %>

app/views/cart/index.html.erb
<div class="container">

  <h1><%= t('views.cart.title') %></h1>

  <h3><%= t('views.cart.description') %></h3>

  <section class="widget">
    <div class="widget-body">
      <div id="carts_stats_list" style="padding-top: 20px"><%= render "carts_stats" %></div>
    </div>
  </section>

  <section class="widget">
    <div class="widget-body">
      <h4 style="padding-top: 20px; color: green"><strong><%= t('views.cart.total_price') + ': ' +  number_to_currency(@total_amount.to_f/100) %></strong></h4>
    </div>
  </section>

  <section class="widget" style="margin-top: 5%">
    <div class="widget-body">
      <%= link_to t('views.catalog.goto'), catalogs_path, class:"btn btn-primary" %>
    </div>
  </section>
</div>

app/views/cart/index.js.erb
$('#carts_stats_list').html('<%= escape_javascript(render("carts_stats")) %>');

app/views/catalogs/index.html.erb
<div class="container">
  <h1><%= t('views.catalog.title') %></h1>

  <h3><%= t('views.catalog.description') %></h3>

    <section class="widget" style="margin-top: 5%">
      <div class="widget-body">
        <% @catalogs.each do |catalog| %>
          <div class="col-md-4 float-left">
            <fieldset>
              <header><h5><%= catalog.title %></h5></header>
              <%= image_tag (catalog.image), style:"width: 250px; height:250px; margin-bottom: 16px; margin-top: 16px" %>

              <p><%= truncate(catalog.description, :length => 75, :separator => ' ') %></p>
              <p class="text-center"><%= number_to_currency(catalog.price.to_f/100) %></p>
              <p><i class="fa fa-minus-circle"></i><input type="number" readonly><i class="fa fa-plus-circle"></i></p>
            </fieldset>
          </div>
        <% end %>

        <%= link_to "Get Price", "", class:"btn btn-primary" %>
      </div>
    </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta charset="utf-8" />
    <title><%= t('views.layouts.welcome') %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= stylesheet_link_tag    "application", charset: "UTF-8", :media => "all", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "application", charset: "UTF-8" %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>  </body>
    <!--DataTables CSS-->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.4.2/css/buttons.dataTables.min.css">
    <!--DataTables JS-->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.turbolinks/2.1.0/jquery.turbolinks.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.flash.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.colVis.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-primary bg-dark">
      <div class="navbar-brand"><%= image_tag ('cabify-logo.png'), style:"height:30px" %></div>
    </nav>
    <div class="wrapper" style="min-height: 100%; height: auto !important; height: 100%; margin: 0 auto -50px;">
      <div class="proper-content">

        <div id="main" class="container clear-top">
          <% if flash[:alert] %>
            <div class="alert alert-danger">
              <%= flash[:alert] %>
            </div>
          <% end %>

          <% if flash[:notice] %>
            <div class="alert alert-success">
              <%= flash[:notice] %>
            </div>
          <% end %>
          <%= yield %>
        </div>

      </div><!-- /.proper_content -->
      <div class="push" style="height:50px;"></div>
    </div><!-- /.wrapper -->
  </body>
</html>